version: '3'
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=mysql
  desconto:
    build:
      context: .
      dockerfile: Dockerfile.desconto
    ports:
      - 11443:11443
    depends_on:
      - database
  listagem:
    build:
      context: .
      dockerfile: Dockerfile.listagem
    environment:
      - DISCOUNT_SERVICE_HOST=desconto:11443
    links:
      - desconto:desconto
    depends_on:
      - desconto
    ports:
      - 11080:11080
