version: '3'
services:
  desconto:
    build:
      context: .
      dockerfile: Dockerfile.desconto
    ports:
      - 11443:11443
  listagem:
    build:
      context: .
      dockerfile: Dockerfile.listagem
    environment:
      - DISCOUNT_SERVICE_HOST=desconto:11443
    links:
      - desconto:desconto
    depends_on:
      - desconto
    ports:
      - 11080:11080
