# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dmsec_pb2 as dmsec__pb2


class DescontoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AplicarDesconto = channel.unary_unary(
        '/dmsec.Desconto/AplicarDesconto',
        request_serializer=dmsec__pb2.DescontoRequisicao.SerializeToString,
        response_deserializer=dmsec__pb2.DescontoResposta.FromString,
        )


class DescontoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AplicarDesconto(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DescontoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AplicarDesconto': grpc.unary_unary_rpc_method_handler(
          servicer.AplicarDesconto,
          request_deserializer=dmsec__pb2.DescontoRequisicao.FromString,
          response_serializer=dmsec__pb2.DescontoResposta.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dmsec.Desconto', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
