# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dmsec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dmsec.proto',
  package='dmsec',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x64msec.proto\x12\x05\x64msec\"N\n\x07\x43liente\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x10\n\x08\x62irthday\x18\x04 \x01(\t\"\x7f\n\x07Produto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x16\n\x0eprice_in_cents\x18\x04 \x01(\x05\x12,\n\x0e\x64iscount_value\x18\x05 \x01(\x0b\x32\x14.dmsec.DiscountValue\"4\n\rDiscountValue\x12\x0b\n\x03pct\x18\x01 \x01(\x02\x12\x16\n\x0evalue_in_cents\x18\x02 \x01(\x05\"V\n\x12\x44\x65scontoRequisicao\x12\x1f\n\x07\x63liente\x18\x01 \x01(\x0b\x32\x0e.dmsec.Cliente\x12\x1f\n\x07produto\x18\x02 \x01(\x0b\x32\x0e.dmsec.Produto\"3\n\x10\x44\x65scontoResposta\x12\x1f\n\x07produto\x18\x01 \x01(\x0b\x32\x0e.dmsec.Produto2S\n\x08\x44\x65sconto\x12G\n\x0f\x41plicarDesconto\x12\x19.dmsec.DescontoRequisicao\x1a\x17.dmsec.DescontoResposta\"\x00\x62\x06proto3')
)




_CLIENTE = _descriptor.Descriptor(
  name='Cliente',
  full_name='dmsec.Cliente',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dmsec.Cliente.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='dmsec.Cliente.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='dmsec.Cliente.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='dmsec.Cliente.birthday', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=100,
)


_PRODUTO = _descriptor.Descriptor(
  name='Produto',
  full_name='dmsec.Produto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dmsec.Produto.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='dmsec.Produto.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='dmsec.Produto.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_in_cents', full_name='dmsec.Produto.price_in_cents', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discount_value', full_name='dmsec.Produto.discount_value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=229,
)


_DISCOUNTVALUE = _descriptor.Descriptor(
  name='DiscountValue',
  full_name='dmsec.DiscountValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pct', full_name='dmsec.DiscountValue.pct', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_in_cents', full_name='dmsec.DiscountValue.value_in_cents', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=283,
)


_DESCONTOREQUISICAO = _descriptor.Descriptor(
  name='DescontoRequisicao',
  full_name='dmsec.DescontoRequisicao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cliente', full_name='dmsec.DescontoRequisicao.cliente', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='produto', full_name='dmsec.DescontoRequisicao.produto', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=371,
)


_DESCONTORESPOSTA = _descriptor.Descriptor(
  name='DescontoResposta',
  full_name='dmsec.DescontoResposta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='produto', full_name='dmsec.DescontoResposta.produto', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=424,
)

_PRODUTO.fields_by_name['discount_value'].message_type = _DISCOUNTVALUE
_DESCONTOREQUISICAO.fields_by_name['cliente'].message_type = _CLIENTE
_DESCONTOREQUISICAO.fields_by_name['produto'].message_type = _PRODUTO
_DESCONTORESPOSTA.fields_by_name['produto'].message_type = _PRODUTO
DESCRIPTOR.message_types_by_name['Cliente'] = _CLIENTE
DESCRIPTOR.message_types_by_name['Produto'] = _PRODUTO
DESCRIPTOR.message_types_by_name['DiscountValue'] = _DISCOUNTVALUE
DESCRIPTOR.message_types_by_name['DescontoRequisicao'] = _DESCONTOREQUISICAO
DESCRIPTOR.message_types_by_name['DescontoResposta'] = _DESCONTORESPOSTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cliente = _reflection.GeneratedProtocolMessageType('Cliente', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTE,
  '__module__' : 'dmsec_pb2'
  # @@protoc_insertion_point(class_scope:dmsec.Cliente)
  })
_sym_db.RegisterMessage(Cliente)

Produto = _reflection.GeneratedProtocolMessageType('Produto', (_message.Message,), {
  'DESCRIPTOR' : _PRODUTO,
  '__module__' : 'dmsec_pb2'
  # @@protoc_insertion_point(class_scope:dmsec.Produto)
  })
_sym_db.RegisterMessage(Produto)

DiscountValue = _reflection.GeneratedProtocolMessageType('DiscountValue', (_message.Message,), {
  'DESCRIPTOR' : _DISCOUNTVALUE,
  '__module__' : 'dmsec_pb2'
  # @@protoc_insertion_point(class_scope:dmsec.DiscountValue)
  })
_sym_db.RegisterMessage(DiscountValue)

DescontoRequisicao = _reflection.GeneratedProtocolMessageType('DescontoRequisicao', (_message.Message,), {
  'DESCRIPTOR' : _DESCONTOREQUISICAO,
  '__module__' : 'dmsec_pb2'
  # @@protoc_insertion_point(class_scope:dmsec.DescontoRequisicao)
  })
_sym_db.RegisterMessage(DescontoRequisicao)

DescontoResposta = _reflection.GeneratedProtocolMessageType('DescontoResposta', (_message.Message,), {
  'DESCRIPTOR' : _DESCONTORESPOSTA,
  '__module__' : 'dmsec_pb2'
  # @@protoc_insertion_point(class_scope:dmsec.DescontoResposta)
  })
_sym_db.RegisterMessage(DescontoResposta)



_DESCONTO = _descriptor.ServiceDescriptor(
  name='Desconto',
  full_name='dmsec.Desconto',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=426,
  serialized_end=509,
  methods=[
  _descriptor.MethodDescriptor(
    name='AplicarDesconto',
    full_name='dmsec.Desconto.AplicarDesconto',
    index=0,
    containing_service=None,
    input_type=_DESCONTOREQUISICAO,
    output_type=_DESCONTORESPOSTA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DESCONTO)

DESCRIPTOR.services_by_name['Desconto'] = _DESCONTO

# @@protoc_insertion_point(module_scope)
