// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dmsec.proto

/*
Package dmsec is a generated protocol buffer package.

It is generated from these files:
	dmsec.proto

It has these top-level messages:
	Cliente
	Produto
	DiscountValue
	DescontoRequisicao
	DescontoResposta
*/
package dmsec

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cliente struct {
	Id        int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Birthday  string `protobuf:"bytes,4,opt,name=birthday" json:"birthday,omitempty"`
}

func (m *Cliente) Reset()                    { *m = Cliente{} }
func (m *Cliente) String() string            { return proto.CompactTextString(m) }
func (*Cliente) ProtoMessage()               {}
func (*Cliente) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Cliente) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Cliente) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Cliente) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Cliente) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

type Produto struct {
	Id            int32          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title         string         `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description   string         `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	PriceInCents  int32          `protobuf:"varint,4,opt,name=price_in_cents,json=priceInCents" json:"price_in_cents,omitempty"`
	DiscountValue *DiscountValue `protobuf:"bytes,5,opt,name=discount_value,json=discountValue" json:"discount_value,omitempty"`
}

func (m *Produto) Reset()                    { *m = Produto{} }
func (m *Produto) String() string            { return proto.CompactTextString(m) }
func (*Produto) ProtoMessage()               {}
func (*Produto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Produto) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Produto) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Produto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Produto) GetPriceInCents() int32 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

func (m *Produto) GetDiscountValue() *DiscountValue {
	if m != nil {
		return m.DiscountValue
	}
	return nil
}

type DiscountValue struct {
	Pct          float32 `protobuf:"fixed32,1,opt,name=pct" json:"pct,omitempty"`
	ValueInCents int32   `protobuf:"varint,2,opt,name=value_in_cents,json=valueInCents" json:"value_in_cents,omitempty"`
}

func (m *DiscountValue) Reset()                    { *m = DiscountValue{} }
func (m *DiscountValue) String() string            { return proto.CompactTextString(m) }
func (*DiscountValue) ProtoMessage()               {}
func (*DiscountValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DiscountValue) GetPct() float32 {
	if m != nil {
		return m.Pct
	}
	return 0
}

func (m *DiscountValue) GetValueInCents() int32 {
	if m != nil {
		return m.ValueInCents
	}
	return 0
}

type DescontoRequisicao struct {
	Cliente *Cliente `protobuf:"bytes,1,opt,name=cliente" json:"cliente,omitempty"`
	Produto *Produto `protobuf:"bytes,2,opt,name=produto" json:"produto,omitempty"`
}

func (m *DescontoRequisicao) Reset()                    { *m = DescontoRequisicao{} }
func (m *DescontoRequisicao) String() string            { return proto.CompactTextString(m) }
func (*DescontoRequisicao) ProtoMessage()               {}
func (*DescontoRequisicao) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DescontoRequisicao) GetCliente() *Cliente {
	if m != nil {
		return m.Cliente
	}
	return nil
}

func (m *DescontoRequisicao) GetProduto() *Produto {
	if m != nil {
		return m.Produto
	}
	return nil
}

type DescontoResposta struct {
	Produto *Produto `protobuf:"bytes,1,opt,name=produto" json:"produto,omitempty"`
}

func (m *DescontoResposta) Reset()                    { *m = DescontoResposta{} }
func (m *DescontoResposta) String() string            { return proto.CompactTextString(m) }
func (*DescontoResposta) ProtoMessage()               {}
func (*DescontoResposta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DescontoResposta) GetProduto() *Produto {
	if m != nil {
		return m.Produto
	}
	return nil
}

func init() {
	proto.RegisterType((*Cliente)(nil), "dmsec.Cliente")
	proto.RegisterType((*Produto)(nil), "dmsec.Produto")
	proto.RegisterType((*DiscountValue)(nil), "dmsec.DiscountValue")
	proto.RegisterType((*DescontoRequisicao)(nil), "dmsec.DescontoRequisicao")
	proto.RegisterType((*DescontoResposta)(nil), "dmsec.DescontoResposta")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Desconto service

type DescontoClient interface {
	AplicarDesconto(ctx context.Context, in *DescontoRequisicao, opts ...grpc.CallOption) (*DescontoResposta, error)
}

type descontoClient struct {
	cc *grpc.ClientConn
}

func NewDescontoClient(cc *grpc.ClientConn) DescontoClient {
	return &descontoClient{cc}
}

func (c *descontoClient) AplicarDesconto(ctx context.Context, in *DescontoRequisicao, opts ...grpc.CallOption) (*DescontoResposta, error) {
	out := new(DescontoResposta)
	err := grpc.Invoke(ctx, "/dmsec.Desconto/AplicarDesconto", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Desconto service

type DescontoServer interface {
	AplicarDesconto(context.Context, *DescontoRequisicao) (*DescontoResposta, error)
}

func RegisterDescontoServer(s *grpc.Server, srv DescontoServer) {
	s.RegisterService(&_Desconto_serviceDesc, srv)
}

func _Desconto_AplicarDesconto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescontoRequisicao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DescontoServer).AplicarDesconto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dmsec.Desconto/AplicarDesconto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DescontoServer).AplicarDesconto(ctx, req.(*DescontoRequisicao))
	}
	return interceptor(ctx, in, info, handler)
}

var _Desconto_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dmsec.Desconto",
	HandlerType: (*DescontoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AplicarDesconto",
			Handler:    _Desconto_AplicarDesconto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dmsec.proto",
}

func init() { proto.RegisterFile("dmsec.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x6b, 0xe3, 0x30,
	0x10, 0x85, 0xd7, 0xce, 0x7a, 0x93, 0x8c, 0x37, 0xde, 0x20, 0x02, 0xeb, 0xa6, 0x14, 0x8c, 0xe9,
	0xc1, 0xa7, 0x1c, 0xd2, 0x63, 0x7b, 0x29, 0x09, 0x84, 0x5e, 0x4a, 0x51, 0xa1, 0x57, 0xa3, 0x48,
	0x2a, 0x19, 0x70, 0x24, 0xc7, 0x92, 0x0b, 0xfd, 0x5f, 0xfd, 0x81, 0xc5, 0xb2, 0xdd, 0xa4, 0x04,
	0x7a, 0xf3, 0xbc, 0x4f, 0x33, 0xef, 0x79, 0x24, 0x08, 0xc5, 0xde, 0x48, 0xbe, 0x28, 0x2b, 0x6d,
	0x35, 0x09, 0x5c, 0x91, 0x1e, 0x60, 0xb8, 0x2a, 0x50, 0x2a, 0x2b, 0x49, 0x04, 0x3e, 0x8a, 0xd8,
	0x4b, 0xbc, 0x2c, 0xa0, 0x3e, 0x0a, 0x72, 0x05, 0xf0, 0x8a, 0x95, 0xb1, 0xb9, 0x62, 0x7b, 0x19,
	0xfb, 0x89, 0x97, 0x8d, 0xe9, 0xd8, 0x29, 0x8f, 0x6c, 0x2f, 0xc9, 0x25, 0x8c, 0x0b, 0xd6, 0xd3,
	0x81, 0xa3, 0xa3, 0x46, 0x70, 0x70, 0x0e, 0xa3, 0x2d, 0x56, 0x76, 0x27, 0xd8, 0x7b, 0xfc, 0xbb,
	0x65, 0x7d, 0x9d, 0x7e, 0x78, 0x30, 0x7c, 0xaa, 0xb4, 0xa8, 0xad, 0x3e, 0xf3, 0x9c, 0x41, 0x60,
	0xd1, 0x16, 0xbd, 0x5d, 0x5b, 0x90, 0x04, 0x42, 0x21, 0x0d, 0xaf, 0xb0, 0xb4, 0xa8, 0x55, 0x67,
	0x76, 0x2a, 0x91, 0x6b, 0x88, 0xca, 0x0a, 0xb9, 0xcc, 0x51, 0xe5, 0x5c, 0x2a, 0x6b, 0x9c, 0x6b,
	0x40, 0xff, 0x3a, 0xf5, 0x41, 0xad, 0x1a, 0x8d, 0xdc, 0x42, 0x24, 0xd0, 0x70, 0x5d, 0x2b, 0x9b,
	0xbf, 0xb1, 0xa2, 0x96, 0x71, 0x90, 0x78, 0x59, 0xb8, 0x9c, 0x2d, 0xda, 0xcd, 0xac, 0x3b, 0xf8,
	0xd2, 0x30, 0x3a, 0x11, 0xa7, 0x65, 0xba, 0x81, 0xc9, 0x37, 0x4e, 0xa6, 0x30, 0x28, 0xb9, 0x75,
	0xe1, 0x7d, 0xda, 0x7c, 0x36, 0x29, 0xdc, 0xd8, 0x63, 0x0a, 0xbf, 0x4d, 0xe1, 0xd4, 0x2e, 0x45,
	0xba, 0x03, 0xb2, 0x96, 0x86, 0x6b, 0x65, 0x35, 0x95, 0x87, 0x1a, 0x0d, 0x72, 0xa6, 0x49, 0x06,
	0x43, 0xde, 0x5e, 0x84, 0x9b, 0x18, 0x2e, 0xa3, 0x2e, 0x54, 0x77, 0x3d, 0xb4, 0xc7, 0xcd, 0xc9,
	0xb2, 0x5d, 0x9f, 0x1b, 0x7f, 0x3c, 0xd9, 0x2d, 0x95, 0xf6, 0x38, 0xbd, 0x83, 0xe9, 0xd1, 0xc9,
	0x94, 0xda, 0x58, 0x76, 0xda, 0xed, 0xfd, 0xd8, 0xbd, 0x7c, 0x86, 0x51, 0xdf, 0x4d, 0x36, 0xf0,
	0xef, 0xbe, 0x2c, 0x90, 0xb3, 0xea, 0x4b, 0xba, 0xe8, 0x97, 0x76, 0xf6, 0x2f, 0xf3, 0xff, 0x67,
	0xa8, 0x35, 0x4f, 0x7f, 0x6d, 0xff, 0xb8, 0xd7, 0x77, 0xf3, 0x19, 0x00, 0x00, 0xff, 0xff, 0x4b,
	0xb0, 0x60, 0x7f, 0x8c, 0x02, 0x00, 0x00,
}
